[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cyfi-nmr"
authors = [{name = "Henning Schröder", email = "henning.schroeder2@uni-rostock.de"}]
dynamic = ["version", "description"]
